driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  parallelism: 4

provisioner:
  name: terraform

platforms:
  - name: aws

suites:
  - name: "awspec"
    verifier:
      name: awspec
      patterns:
        - "test/integration/kt_suite/test_s3.rb"